[phases.setup]
nixPkgs = [
  "php",
  "php-bcmath",
  "php-curl",
  "php-dom",
  "php-mbstring",
  "php-pdo",
  "php-pdo_mysql",
  "php-tokenizer",
  "php-xml",
  "wget",       # để tải composer
  "unzip"       # để giải nén composer
]

[phases.install]
cmds = [
  "wget https://getcomposer.org/installer -O composer-setup.php",
  "php composer-setup.php --install-dir=/usr/local/bin --filename=composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"