[phases.setup]
nixPkgs = ["php", "composer", "php-curl", "php-mbstring", "php-dom", "php-pdo", "php-pdo_mysql", "php-tokenizer", "php-xml", "php-bcmath"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "php artisan config:cache"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"